GET https://register.fca.org.uk/s/sfsites/aura?r=1&other.ShPo_LEX_Reg_Search.getAllFirmProfileHeaderMetadata=1&other.ShPo_LEX_Reg_Search.getFirmDetails=1&other.ShPo_LEX_Reg_Utilities.getStaticResrouceFile=65
